package Package1;

import java.net.InetSocketAddress;

public class Class2 {
    public static void main(String[] args) {
        Class1 obj1 = new Class1();

        obj1.Attribute1=15;
        // Encapsulate
        Class1 obj = new Class1();

        //obj.a=1000; Attribute a, is now private so is hidden for this class
        obj.SetAge(10);//thanks to Setter Method, now I can set a value on the private Attribute
        System.out.println("The Age is: "+obj.GetAge());
        //Testing the Setter and Getter generated by IDE
        obj.setName("Adrian");
        System.out.println("The name is: "+obj.getName());
    }
}
