// Access Modifiers
package Package1;

public class Class1 {
    //Attributes
    public int Attribute1; //can be used by any class that imports this package
    private int Attribute2; // can not be used by class outside of package or this class, so other classes on this same package can not use this Attribute
    // Encapsulate and Access Modifiers(Setters and Getters)
    private int a; // prevent errors of assignation on other classes, we can encapsulate this, change to private to hide it from other classes
    private String name; // IDE can help us to create Setters and Getters
    //Setters:
    public void SetAge(int a){ // now other classes can be set using a method, this is called a Setter
        this.a=a;
    }

    //Getters:
    public int GetAge(){ //Method Getter to Display the Private Attribute
        return a;
    }

    public void setName(String name) {// generated by IDE
        this.name = name;
    }

    public String getName() { // generated by IDE
        return name;
    }
    // TIP: Classes are saved with first Letter UpperCase, but in methods the first letter is on LowerCase
}
